--DROP TABLE IF EXISTS SPEAKER;
--create table SPEAKER (ID INT AUTO_INCREMENT  PRIMARY KEY,FIRST_NAME VARCHAR(250) NOT NULL,LAST_NAME VARCHAR(250) NOT NULL,TWITTER VARCHAR(250) DEFAULT NULL);
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (1, 'surender', 'Singh', 'test1');
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (2, 'surender', 'Singh', 'test2');
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (3, 'surender', 'Singh', 'test3');
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (4, 'surender', 'Singh', 'test4');
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (5, 'surender', 'Singh', 'test5');
INSERT INTO SPEAKER(ID, FIRST_NAME, LAST_NAME, TWITTER) values (6, 'surender', 'Singh', 'test6');
